### ISSUE TITLE
"500 Internal Server Error" if running on ibm fhir server with basic authentication credentials

### ISSUE THREAD

**Issue by gk-zhang** [JohannesOehm/FhirExtinguisher#6]
Dear FhirExtinguisher team,

we are running FhirExtinguisher on the top of our local ibm fhir server by doing:

`java -jar FhirExtinguisher-1.5.2-all.jar -f https://servername/fhir-server/api/v4 -p 8081 -a username:password `

Here the "username:password" is necessary to login to the ibm fhir server.

The web user interface is running under "http://localhost:8081". However it showed the following error message wher search for Patient fhir resources:

```
Error:

500 Internal Server Error
connection: keep-alive
content-length: 2212
content-type: text/plain; charset=UTF-8


FhirExtinguisher/Ktor-Client-Exception: Cannot redirect to 'https://servername/fhir-server/api/v4/Patient?'!
 
io.ktor.client.features.ClientRequestException: Client request(https://servername/fhir-server/api/v4/Patient?) invalid: 401 Unauthorized. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:38)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:54)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:129)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion$create$factory$1$1.run(NettyApplicationEngine.kt:227)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
``` 

Do you what could be the issue there?

**Comment by JohannesOehm** [comment]
Internally, there is the `/redirect`-endpoint, which uses Ktor client library and acts like a reverse proxy, which just forwards the raw data returned by the FHIR server (this is done to prevent the user from having to enable CORS on the FHIR server). And there is the `/fhir`-endpoint, which uses the HAPI client library. I had to rewrite the Ktor-reverse proxy, maybe I forgot to add the basic auth credentials there.

Can you try to configure the columns without the preview and then just hit the download button?

**Comment by gk-zhang** [comment]
> 
> 
> Internally, there is the `/redirect`-endpoint, which uses Ktor client library and acts like a reverse proxy, which just forwards the raw data returned by the FHIR server (this is done to prevent the user from having to enable CORS on the FHIR server). And there is the `/fhir`-endpoint, which uses the HAPI client library. I had to rewrite the Ktor-reverse proxy, maybe I forgot to add the basic auth credentials there.
> 
> Can you try to configure the columns without the preview and then just hit the download button?

Hi, thanks a lot for the quick reply.
I got these error messages when I hit "enter" key in the search field or click "GET".
I assume that you want to me NOT to do these, but click directly "Download" button? Yes, the download seems to be working and I can have a csv file with the default columns. 

However, if I have added more columns, such as "gender" and search for "Patient?gender=male", clicking "Download" button will show the following error message in a separate tab on web browser:
```
Error: Failed to parse response from server when performing GET to URL https://servername/fhir-server/api/v4/Patient?gender=male - java.net.UnknownHostException: servername: Temporary failure in name resolution
```

**Comment by JohannesOehm** [comment]
Hey, I created a new version which should fix the issue. Can you try if the preview function will work with the new one?

**Comment by gk-zhang** [comment]
Hi, with the new release you just pushed, the preview is now working without search options. 
That is, it is working with "Patient?".
But if it is "Patient?gender=male" in the search field, it still returned errors as following:

```
Error:

500 Internal Server Error
connection: keep-alive
content-length: 1956
content-type: text/plain; charset=UTF-8


FhirExtinguisher/Ktor-Client-Exception: Cannot redirect to 'https://servername/fhir-server/api/v4/Patient?gender=female'!
 
io.ktor.network.sockets.SocketTimeoutException: Socket timeout has been expired [url=https://servername/fhir-server/api/v4/Patient?gender=female, socket_timeout=unknown] ms
	at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(HttpTimeout.kt:209)
	at io.ktor.client.engine.apache.ApacheHttpRequestKt.mapCause(ApacheHttpRequest.kt:62)
	at io.ktor.client.engine.apache.ApacheRequestProducer.failed(ApacheRequestProducer.kt:70)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:98)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: 30.000 milliseconds timeout on connection http-outgoing-17 [ACTIVE]
	... 11 more
```

**Comment by JohannesOehm** [comment]
The error below is due to long response times of the FHIR server (currently, the timeout is set to 30 seconds). I increased the timeout of FhirExtinguisher to 60 seconds. But I would recommend checking your FHIR servers configuration, such a long response time feels odd.

**Comment by gk-zhang** [comment]
> 
> 
> The error below is due to long response times of the FHIR server (currently, the timeout is set to 30 seconds). I increased the timeout of FhirExtinguisher to 60 seconds. But I would recommend checking your FHIR servers configuration, such a long response time feels odd.

Yes, it seems to be the timeout issue. This is unfortunately how our local fhir server is behaving.  
Now with the release "v1.5.4", it is working and many thanks!
Does it mean, however, if there is a complex fhir search and it takes more than 60 seconds, this error will probably show again?

**Comment by JohannesOehm** [comment]
Yes, the error would come again. I released a new version, where you can configure the timeout using a new command line parameter (`-t`).

**Comment by gk-zhang** [comment]
> 
> 
> Yes, the error would come again. I released a new version, where you can configure the timeout using a new command line parameter (`-t`).

**Comment by gk-zhang** [comment]
> 
> 
> Yes, the error would come again. I released a new version, where you can configure the timeout using a new command line parameter (`-t`).

This is very nice and thanks a lot!
